In [44]:
# create a class
import torch
import torch.nn as nn   

class Model(nn.Module):              # inherit from nn.Module (gives automatic weight/gradient handling)

    def __init__(self, num_features):
        super().__init__()           # MUST call this - activates nn.Module's machinery (never skip)

        # nn.Linear(in, out) - a fully-connected layer that AUTO-creates weights & bias
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()  # squashes output to 0-1 (a probability)

    def forward(self, features):   
        out = self.linear(features)  # weighted sum (z = Wx + b), done automatically
        out = self.sigmoid(out)      # sigmoid activation 
        return out
        

In [45]:
# create a dataset
features=torch.rand(10,5)

In [46]:
features.shape[1]

5

In [47]:
# create a model 
model=Model(features.shape[1])

# this returns 10 predictions (one probability per sample)
model(features)

tensor([[0.5199],
        [0.4357],
        [0.4279],
        [0.4315],
        [0.4279],
        [0.5312],
        [0.5311],
        [0.5899],
        [0.5488],
        [0.4494]], grad_fn=<SigmoidBackward0>)

#### Why model(features) and not model.forward(features)?

#### Both work, but model(features) is the correct professional way. When you call model(features), PyTorch runs forward() plus important internal hooks (needed for some features). Always use model(features), not model.forward(features) directly.

In [48]:
model.linear.weight

Parameter containing:
tensor([[ 0.2972,  0.3802,  0.2913, -0.2628,  0.0608]], requires_grad=True)

In [49]:
model.linear.bias

Parameter containing:
tensor([-0.3995], requires_grad=True)

In [50]:
! pip install torchinfo

In [52]:
from torchinfo import summary 
summary (model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00