In [418]:
import torch
print(torch.__version__)


2.12.1


In [419]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a tensor

In [420]:
# torch.empty - reserves memory for the tensor but does NOT set the values
# so it contains whatever random numbers were already in that memory
x=torch.empty(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [421]:
# check type
type(x)

torch.Tensor

In [422]:
# torch.zeros - filled entirely with 0s
torch.zeros(5,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [423]:
# torch.ones - filled entirely with 1s
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [424]:
# torch.rand - random values between 0 and 1
torch.rand(2,3)

tensor([[0.0115, 0.3045, 0.3893],
        [0.9897, 0.6779, 0.5748]])

## Reproducibility (seeds):

In [425]:
# rand gives DIFFERENT numbers each run.
# manual_seed fixes the randomness so you get the SAME numbers every time
# (crucial for consistent, repeatable experiments)
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [426]:
torch.manual_seed(100)
torch.rand(3,3) # Same output because the seed is reset to 100

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [427]:
#torch.tensor - build directly from a list of lists (your own data)
torch.tensor([[1,4,5,8],[9,4,2,71]])

tensor([[ 1,  4,  5,  8],
        [ 9,  4,  2, 71]])

In [428]:
# arange(start, stop, step)
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [429]:
# linspace(start, stop, count) - 'count' evenly spaced numbers
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [430]:
# eye(n) - identity matrix (1s on diagonal, 0s elsewhere)
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [431]:
# full(shape, value) - shape filled with a single value
torch.full((2,3),6)

tensor([[6, 6, 6],
        [6, 6, 6]])

## Tensor Shapes

In [432]:
x=torch.tensor([[1,2,4,6],[5,6,7,4]])
x

tensor([[1, 2, 4, 6],
        [5, 6, 7, 4]])

In [433]:
x.shape # 2 rows and 4 columns 

torch.Size([2, 4])

In [434]:
# _like functions: make a new tensor with the SAME shape as x
print(torch.empty_like(x)) # empty, same shape
print(torch.zeros_like(x))   # zeros, same shape
print(torch.ones_like(x))     # ones, same shape
print(torch.rand_like(x, dtype=torch.float32))   # random; dtype needed (x is int)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.1180, 0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014, 0.9969]])


## Tensor Data Types

In [435]:
x.dtype #check the data type

torch.int64

In [436]:
# assign dtype while creating a tensor 
print(torch.tensor([[1,2,5,9],[3,45,53,2]],dtype=torch.float64))
print(torch.tensor([[1.3,4.6,3.5],[2.9,4.1,9.6]], dtype=torch.int64))

tensor([[ 1.,  2.,  5.,  9.],
        [ 3., 45., 53.,  2.]], dtype=torch.float64)
tensor([[1, 4, 3],
        [2, 4, 9]])


In [437]:
# .to(dtype) - CONVERT an existing tensor to a different type
x.to(torch.float64)

tensor([[1., 2., 4., 6.],
        [5., 6., 7., 4.]], dtype=torch.float64)

#  PyTorch Tensor Data Types (dtypes)

| Type | Meaning | When Used |
|------|---------|-----------|
| `torch.float32` | 32-bit float | **Default** for deep learning |
| `torch.float64` | 64-bit float | High-precision tasks |
| `torch.float16` | 16-bit float | Mixed-precision (saves GPU memory) |
| `torch.int64` | 64-bit integer | Indices (default int) |
| `torch.uint8` | 8-bit unsigned | Image pixels (0–255) |
| `torch.bool` | True/False | Masks for logic |

## Mathematical Operations

In [438]:
#Scalar Operations — apply one number to every element
torch.manual_seed(100)
z=torch.rand(2,3)
print(z)
print(z+2)
print(z-2)
print(z*2)
print(z/3)
print(z%3)
print((z*100)//3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[2.1117, 2.8158, 2.2626],
        [2.4839, 2.6765, 2.7539]])
tensor([[-1.8883, -1.1842, -1.7374],
        [-1.5161, -1.3235, -1.2461]])
tensor([[0.2233, 1.6317, 0.5251],
        [0.9678, 1.3530, 1.5078]])
tensor([[0.0372, 0.2719, 0.0875],
        [0.1613, 0.2255, 0.2513]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[ 3., 27.,  8.],
        [16., 22., 25.]])


In [439]:
# Element-wise Operations — combine two SAME-shape tensors, position by position
torch.manual_seed(100)
a=torch.rand(2,3)
torch.manual_seed(101)
b=torch.rand(2,3)
print(a)
print(b)
print(a+b) # a[i]+b[i] at each position
print(a-b)
print(a*b) # element-wise multiply (NOT matrix multiply)
print(a/b)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[0.3097, 1.2661, 0.3535],
        [1.3711, 0.9659, 0.7725]])
tensor([[-0.0864,  0.3656,  0.1717],
        [-0.4033,  0.3871,  0.7353]])
tensor([[0.0221, 0.3674, 0.0239],
        [0.4293, 0.1958, 0.0140]])
tensor([[ 0.5638,  1.8118,  2.8884],
        [ 0.5454,  2.3376, 40.5538]])


In [440]:
c = torch.tensor([1, -2, 3, -4]) 
torch.abs(c) # absolute value -> [1,2,3,4] (makes positive)

tensor([1, 2, 3, 4])

In [441]:
torch.neg(c) # negate -> [-1,2,-3,4] (flips sign)

tensor([-1,  2, -3,  4])

In [442]:
d = torch.tensor([1.9, 2.2, 3.7, 4.4])
torch.round(d) # round to nearest -> [2,2,4,4]

tensor([2., 2., 4., 4.])

In [443]:
torch.ceil(d) # always round UP -> [2,3,4,5]

tensor([2., 3., 4., 5.])

In [444]:
torch.floor(d) # always round DOWN -> [1,2,3,4]

tensor([1., 2., 3., 4.])

In [445]:
d

tensor([1.9000, 2.2000, 3.7000, 4.4000])

In [446]:
torch.clamp(d, min=2, max=3)  # Keep values between 2 and 3

tensor([2.0000, 2.2000, 3.0000, 3.0000])

In [447]:
# torch.randint - random INTEGERS between low and high
# low = smallest possible value (included)
# high = upper limit (NOT included - stops one below)
torch.randint(low=0, high=10, size=(2,3))

tensor([[3, 5, 3],
        [5, 7, 8]])

In [448]:
torch.manual_seed(100)
torch.randint(size=(2,3),low=5,high=10)

tensor([[5, 7, 5],
        [9, 5, 6]])


| Function | Produces | Range |
|----------|----------|-------|
| `torch.rand` | Random decimals (floats) | Between 0 and 1 |
| `torch.randint` | Random whole numbers (integers) | Between low and high |

In [449]:
torch.manual_seed(101)
print(torch.rand(2,3))
torch.manual_seed(105)
print(torch.randint(size=(3,3),low=10,high=15))

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[14, 10, 14],
        [14, 14, 10],
        [12, 13, 14]])
