In [199]:
import torch
print(torch.__version__)


2.12.1


In [200]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a tensor

In [201]:
# torch.empty - reserves memory for the tensor but does NOT set the values
# so it contains whatever random numbers were already in that memory
x=torch.empty(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [202]:
# check type
type(x)

torch.Tensor

In [203]:
# torch.zeros - filled entirely with 0s
torch.zeros(5,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [204]:
# torch.ones - filled entirely with 1s
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [205]:
# torch.rand - random values between 0 and 1
torch.rand(2,3)

tensor([[0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557]])

## Reproducibility (seeds):

In [206]:
# rand gives DIFFERENT numbers each run.
# manual_seed fixes the randomness so you get the SAME numbers every time
# (crucial for consistent, repeatable experiments)
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [207]:
torch.manual_seed(100)
torch.rand(3,3) # Same output because the seed is reset to 100

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [208]:
#torch.tensor - build directly from a list of lists (your own data)
torch.tensor([[1,4,5,8],[9,4,2,71]])

tensor([[ 1,  4,  5,  8],
        [ 9,  4,  2, 71]])

In [209]:
# arange(start, stop, step)
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [210]:
# linspace(start, stop, count) - 'count' evenly spaced numbers
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [211]:
# eye(n) - identity matrix (1s on diagonal, 0s elsewhere)
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [212]:
# full(shape, value) - shape filled with a single value
torch.full((2,3),6)

tensor([[6, 6, 6],
        [6, 6, 6]])

## Tensor Shapes

In [213]:
x=torch.tensor([[1,2,4,6],[5,6,7,4]])
x

tensor([[1, 2, 4, 6],
        [5, 6, 7, 4]])

In [214]:
x.shape # 2 rows and 4 columns 

torch.Size([2, 4])

In [215]:
# _like functions: make a new tensor with the SAME shape as x
print(torch.empty_like(x)) # empty, same shape
print(torch.zeros_like(x))   # zeros, same shape
print(torch.ones_like(x))     # ones, same shape
print(torch.rand_like(x, dtype=torch.float32))   # random; dtype needed (x is int)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.1180, 0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014, 0.9969]])


## Tensor Data Types

In [216]:
x.dtype #check the data type

torch.int64

In [217]:
# assign dtype while creating a tensor 
print(torch.tensor([[1,2,5,9],[3,45,53,2]],dtype=torch.float64))
print(torch.tensor([[1.3,4.6,3.5],[2.9,4.1,9.6]], dtype=torch.int64))

tensor([[ 1.,  2.,  5.,  9.],
        [ 3., 45., 53.,  2.]], dtype=torch.float64)
tensor([[1, 4, 3],
        [2, 4, 9]])


In [218]:
# .to(dtype) - CONVERT an existing tensor to a different type
x.to(torch.float64)

tensor([[1., 2., 4., 6.],
        [5., 6., 7., 4.]], dtype=torch.float64)

#  PyTorch Tensor Data Types (dtypes)

| Type | Meaning | When Used |
|------|---------|-----------|
| `torch.float32` | 32-bit float | **Default** for deep learning |
| `torch.float64` | 64-bit float | High-precision tasks |
| `torch.float16` | 16-bit float | Mixed-precision (saves GPU memory) |
| `torch.int64` | 64-bit integer | Indices (default int) |
| `torch.uint8` | 8-bit unsigned | Image pixels (0–255) |
| `torch.bool` | True/False | Masks for logic |