In [397]:
import torch
print(torch.__version__)


2.12.1


In [398]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a tensor

In [399]:
# torch.empty - reserves memory for the tensor but does NOT set the values
# so it contains whatever random numbers were already in that memory
x=torch.empty(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [400]:
# check type
type(x)

torch.Tensor

In [401]:
# torch.zeros - filled entirely with 0s
torch.zeros(5,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [402]:
# torch.ones - filled entirely with 1s
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [403]:
# torch.rand - random values between 0 and 1
torch.rand(2,3)

tensor([[0.2195, 0.8303, 0.2334],
        [0.1849, 0.8332, 0.8681]])

## Reproducibility (seeds):

In [404]:
# rand gives DIFFERENT numbers each run.
# manual_seed fixes the randomness so you get the SAME numbers every time
# (crucial for consistent, repeatable experiments)
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [405]:
torch.manual_seed(100)
torch.rand(3,3) # Same output because the seed is reset to 100

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [406]:
#torch.tensor - build directly from a list of lists (your own data)
torch.tensor([[1,4,5,8],[9,4,2,71]])

tensor([[ 1,  4,  5,  8],
        [ 9,  4,  2, 71]])

In [407]:
# arange(start, stop, step)
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [408]:
# linspace(start, stop, count) - 'count' evenly spaced numbers
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [409]:
# eye(n) - identity matrix (1s on diagonal, 0s elsewhere)
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [410]:
# full(shape, value) - shape filled with a single value
torch.full((2,3),6)

tensor([[6, 6, 6],
        [6, 6, 6]])

## Tensor Shapes

In [411]:
x=torch.tensor([[1,2,4,6],[5,6,7,4]])
x

tensor([[1, 2, 4, 6],
        [5, 6, 7, 4]])

In [412]:
x.shape # 2 rows and 4 columns 

torch.Size([2, 4])

In [413]:
# _like functions: make a new tensor with the SAME shape as x
print(torch.empty_like(x)) # empty, same shape
print(torch.zeros_like(x))   # zeros, same shape
print(torch.ones_like(x))     # ones, same shape
print(torch.rand_like(x, dtype=torch.float32))   # random; dtype needed (x is int)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.1180, 0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014, 0.9969]])


## Tensor Data Types

In [414]:
x.dtype #check the data type

torch.int64

In [415]:
# assign dtype while creating a tensor 
print(torch.tensor([[1,2,5,9],[3,45,53,2]],dtype=torch.float64))
print(torch.tensor([[1.3,4.6,3.5],[2.9,4.1,9.6]], dtype=torch.int64))

tensor([[ 1.,  2.,  5.,  9.],
        [ 3., 45., 53.,  2.]], dtype=torch.float64)
tensor([[1, 4, 3],
        [2, 4, 9]])


In [416]:
# .to(dtype) - CONVERT an existing tensor to a different type
x.to(torch.float64)

tensor([[1., 2., 4., 6.],
        [5., 6., 7., 4.]], dtype=torch.float64)

#  PyTorch Tensor Data Types (dtypes)

| Type | Meaning | When Used |
|------|---------|-----------|
| `torch.float32` | 32-bit float | **Default** for deep learning |
| `torch.float64` | 64-bit float | High-precision tasks |
| `torch.float16` | 16-bit float | Mixed-precision (saves GPU memory) |
| `torch.int64` | 64-bit integer | Indices (default int) |
| `torch.uint8` | 8-bit unsigned | Image pixels (0–255) |
| `torch.bool` | True/False | Masks for logic |

## Mathematical Operations

In [417]:
#Scalar Operations — apply one number to every element
torch.manual_seed(100)
z=torch.rand(2,3)
print(z)
print(z+2)
print(z-2)
print(z*2)
print(z/3)
print(z%3)
print((z*100)//3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[2.1117, 2.8158, 2.2626],
        [2.4839, 2.6765, 2.7539]])
tensor([[-1.8883, -1.1842, -1.7374],
        [-1.5161, -1.3235, -1.2461]])
tensor([[0.2233, 1.6317, 0.5251],
        [0.9678, 1.3530, 1.5078]])
tensor([[0.0372, 0.2719, 0.0875],
        [0.1613, 0.2255, 0.2513]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[ 3., 27.,  8.],
        [16., 22., 25.]])


In [418]:
# Element-wise Operations — combine two SAME-shape tensors, position by position
torch.manual_seed(100)
a=torch.rand(2,3)
torch.manual_seed(101)
b=torch.rand(2,3)
print(a)
print(b)
print(a+b) # a[i]+b[i] at each position
print(a-b)
print(a*b) # element-wise multiply (NOT matrix multiply)
print(a/b)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[0.3097, 1.2661, 0.3535],
        [1.3711, 0.9659, 0.7725]])
tensor([[-0.0864,  0.3656,  0.1717],
        [-0.4033,  0.3871,  0.7353]])
tensor([[0.0221, 0.3674, 0.0239],
        [0.4293, 0.1958, 0.0140]])
tensor([[ 0.5638,  1.8118,  2.8884],
        [ 0.5454,  2.3376, 40.5538]])


In [419]:
c = torch.tensor([1, -2, 3, -4]) 
torch.abs(c) # absolute value -> [1,2,3,4] (makes positive)

tensor([1, 2, 3, 4])

In [420]:
torch.neg(c) # negate -> [-1,2,-3,4] (flips sign)

tensor([-1,  2, -3,  4])

In [421]:
d = torch.tensor([1.9, 2.2, 3.7, 4.4])
torch.round(d) # round to nearest -> [2,2,4,4]

tensor([2., 2., 4., 4.])

In [422]:
torch.ceil(d) # always round UP -> [2,3,4,5]

tensor([2., 3., 4., 5.])

In [423]:
torch.floor(d) # always round DOWN -> [1,2,3,4]

tensor([1., 2., 3., 4.])

In [424]:
d

tensor([1.9000, 2.2000, 3.7000, 4.4000])

In [425]:
torch.clamp(d, min=2, max=3)  # Keep values between 2 and 3

tensor([2.0000, 2.2000, 3.0000, 3.0000])

In [426]:
# torch.randint - random INTEGERS between low and high
# low = smallest possible value (included)
# high = upper limit (NOT included - stops one below)
torch.randint(low=0, high=10, size=(2,3))

tensor([[3, 5, 3],
        [5, 7, 8]])

In [427]:
torch.manual_seed(100)
torch.randint(size=(2,3),low=5,high=10)

tensor([[5, 7, 5],
        [9, 5, 6]])


| Function | Produces | Range |
|----------|----------|-------|
| `torch.rand` | Random decimals (floats) | Between 0 and 1 |
| `torch.randint` | Random whole numbers (integers) | Between low and high |

In [428]:
torch.manual_seed(101)
print(torch.rand(2,3))
torch.manual_seed(105)
print(torch.randint(size=(3,3),low=10,high=15))

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[14, 10, 14],
        [14, 14, 10],
        [12, 13, 14]])


## Reduction Operations — reduce many numbers into fewer

In [429]:
torch.manual_seed(110)
l=torch.randint(size=(3,3),low=10,high=20,dtype=torch.float64)
l

tensor([[12., 11., 19.],
        [17., 17., 15.],
        [15., 16., 12.]], dtype=torch.float64)

In [430]:
torch.sum(l) # add all elements

tensor(134., dtype=torch.float64)

In [431]:
torch.sum(l,dim=0) # sum DOWN each column

tensor([44., 44., 46.], dtype=torch.float64)

In [432]:
torch.sum(l,dim=1) # sum ACROSS each row

tensor([42., 49., 43.], dtype=torch.float64)

In [433]:
print(torch.mean(l))# average of all elements
print(torch.mean(l,dim=0)) # Average of each column
print(torch.mean(l,dim=1)) # Average of each row

tensor(14.8889, dtype=torch.float64)
tensor([14.6667, 14.6667, 15.3333], dtype=torch.float64)
tensor([14.0000, 16.3333, 14.3333], dtype=torch.float64)


In [434]:
torch.median(l) # middle value

tensor(15., dtype=torch.float64)

In [435]:
print(torch.max(l)) # largest value

tensor(19., dtype=torch.float64)


In [436]:
torch.min(l) # smallest value

tensor(11., dtype=torch.float64)

In [437]:
torch.prod(l)  # multiply all elements together

tensor(3.1312e+10, dtype=torch.float64)

In [438]:
torch.std(l) # standard deviation (spread)

tensor(2.7131, dtype=torch.float64)

In [439]:
torch.var(l)    # variance (spread squared)

tensor(7.3611, dtype=torch.float64)

In [440]:
l

tensor([[12., 11., 19.],
        [17., 17., 15.],
        [15., 16., 12.]], dtype=torch.float64)

In [441]:
# argmax/argmin return the INDEX (position), not the value
print(torch.argmax(l))         # position of the largest
print(torch.argmin(l))         # position of the smallest

tensor(2)
tensor(1)


## Matrix Operations 

In [442]:
torch.manual_seed(120)
f = torch.randint(size=(2,3), low=0, high=10)
print(f)
torch.manual_seed(121)
g = torch.randint(size=(3,2), low=0, high=10)
print(g)
torch.matmul(f, g) # matrix multiplication

tensor([[3, 8, 8],
        [9, 6, 6]])
tensor([[2, 1],
        [6, 9],
        [0, 7]])


tensor([[ 54, 131],
        [ 54, 105]])

In [443]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
torch.dot(vector1, vector2)    # dot product: 1*3 + 2*4 = 11

tensor(11)

In [444]:
f

tensor([[3, 8, 8],
        [9, 6, 6]])

In [445]:
torch.transpose(f,0,1)       # swap dims 0 and 1 (rows <-> columns)

tensor([[3, 9],
        [8, 6],
        [8, 6]])

In [446]:
torch.manual_seed(125)
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(h)
print(torch.det(h))        # determinant 
print(torch.inverse(h))    # inverse 

tensor([[5., 9., 0.],
        [5., 9., 3.],
        [2., 9., 2.]])
tensor(-81.)
tensor([[ 0.1111,  0.2222, -0.3333],
        [ 0.0494, -0.1235,  0.1852],
        [-0.3333,  0.3333,  0.0000]])


## Comparison Operations

In [447]:
torch.manual_seed(85)
i = torch.randint(size=(2,3), low=0, high=10)
print(i)
torch.manual_seed(90)
j = torch.randint(size=(2,3), low=0, high=10)
print(j)

print(i > j)
print(i < j)
print(i == j)
print(i != j)
print(i >= j)
print(i <= j)

tensor([[6, 0, 1],
        [4, 9, 7]])
tensor([[9, 5, 0],
        [1, 9, 9]])
tensor([[False, False,  True],
        [ True, False, False]])
tensor([[ True,  True, False],
        [False, False,  True]])
tensor([[False, False, False],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[False, False,  True],
        [ True,  True, False]])
tensor([[ True,  True, False],
        [False,  True,  True]])


## Special Functions

In [448]:
torch.manual_seed(125)
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 9., 0.],
        [5., 9., 3.]])

In [449]:
torch.log(k) # natural log - used in cross-entropy LOSS

tensor([[1.6094, 2.1972,   -inf],
        [1.6094, 2.1972, 1.0986]])

In [450]:
torch.exp(k) # e^x - used in SOFTMAX

tensor([[1.4841e+02, 8.1031e+03, 1.0000e+00],
        [1.4841e+02, 8.1031e+03, 2.0086e+01]])

In [451]:
torch.sqrt(k) # square root 

tensor([[2.2361, 3.0000, 0.0000],
        [2.2361, 3.0000, 1.7321]])

In [452]:
torch.sigmoid(k) # squashes to 0-1 (binary classification output)

tensor([[0.9933, 0.9999, 0.5000],
        [0.9933, 0.9999, 0.9526]])

In [453]:
# scores -> probabilities (multiclass output)
print(torch.softmax(k,dim=0))
print(torch.softmax(k,dim=1))

tensor([[0.5000, 0.5000, 0.0474],
        [0.5000, 0.5000, 0.9526]])
tensor([[1.7984e-02, 9.8189e-01, 1.2118e-04],
        [1.7943e-02, 9.7963e-01, 2.4283e-03]])


In [454]:
torch.relu(k) # max(0,x) - the default HIDDEN-layer activation

tensor([[5., 9., 0.],
        [5., 9., 3.]])

## In-place Operations

## Functions ending with (_)  modify the tensor directly (in place) instead of returning a new one — saves memory.

In [455]:
torch.manual_seed(70)
m=torch.rand(2,3)
print(m)
torch.manual_seed(80)
n=torch.rand(2,3)
print(n)

tensor([[0.4350, 0.3591, 0.3411],
        [0.2644, 0.6656, 0.1341]])
tensor([[0.6104, 0.0960, 0.0480],
        [0.5372, 0.0865, 0.7079]])


In [456]:
m+n # creates a new tensor 

tensor([[1.0454, 0.4552, 0.3892],
        [0.8016, 0.7521, 0.8420]])

In [457]:
m.add_(n)  # m = m + n, stored back INTO m 

tensor([[1.0454, 0.4552, 0.3892],
        [0.8016, 0.7521, 0.8420]])

In [458]:
m

tensor([[1.0454, 0.4552, 0.3892],
        [0.8016, 0.7521, 0.8420]])

In [459]:
m.relu_() # apply relu directly to m

tensor([[1.0454, 0.4552, 0.3892],
        [0.8016, 0.7521, 0.8420]])

In [460]:
m

tensor([[1.0454, 0.4552, 0.3892],
        [0.8016, 0.7521, 0.8420]])

## Copying a Tensor

In [461]:
torch.manual_seed(71)
a=torch.rand(2,3)
print(a)

tensor([[0.5073, 0.3347, 0.9694],
        [0.7767, 0.9654, 0.5069]])


In [462]:
b=a  #b = a does NOT copy — both names point to the same tensor.
b

tensor([[0.5073, 0.3347, 0.9694],
        [0.7767, 0.9654, 0.5069]])

In [463]:
a[0][0]=12 # changes have been done in a variable here
a 

tensor([[12.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [464]:
b # but b also changes as both the variables are pointing to the same tensor 

tensor([[12.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [465]:
print(id(a),id(b)) # identical ids -> same object

4728376848 4728376848


In [466]:
b=a.clone()

In [467]:
a

tensor([[12.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [468]:
b

tensor([[12.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [469]:
a[0][0]=39 # changes have been done in 'a' variable
a

tensor([[39.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [470]:
b # b stays unchanged 

tensor([[12.0000,  0.3347,  0.9694],
        [ 0.7767,  0.9654,  0.5069]])

In [471]:
print(id(a),id(b)) # different ids -> independent objects

4728376848 4727963728


## b = a shares memory. Use .clone() when you need a separate copy.

## Reshaping

In [472]:
#rearranges the numbers into a new shape 
x = torch.arange(12)  # tensor([0,1,2,...,11]) - 12 numbers in a line
print(x)
print(x.shape)
print(x.reshape(3, 4))        # arrange into 3 rows x 4 cols
print(x.reshape(4, 3))        # or 4 rows x 3 cols
print(x.reshape(2, 6))        # or 2 rows x 6 cols
print(x.reshape(2,2,3))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [473]:
# you can use -1 to auto calculate 
x.reshape(3, -1)   # we have given rows=3, PyTorch figures out cols = 4 automatically

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [474]:
#view() — same as reshape
x = torch.arange(12)
print(x.view(3, 4))    # same result as reshape(3,4)
print(x.view(2, 6))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


##  reshape() and view() both reshape tensors.
##  reshape() is safer, view() is faster.

## squeeze() — remove dimensions of size 1

In [475]:
torch.manual_seed(30)
w=torch.rand(2,3,1)
print(w)
print(w.shape)

tensor([[[0.9007],
         [0.7464],
         [0.4716]],

        [[0.8738],
         [0.7403],
         [0.7840]]])
torch.Size([2, 3, 1])


In [476]:
w.squeeze().shape

torch.Size([2, 3])

In [477]:
# we can also squeeze the specific dimension also
w.squeeze(0).shape  # Remove dim 0 only if its size is 1
# Dim 0 is not removed because its size is 2.

torch.Size([2, 3, 1])

In [478]:
w.squeeze(2).shape

torch.Size([2, 3])

In [479]:
# unsqueeze - add a dimension of size 1
x = torch.rand(226,226,3)            
print(x.unsqueeze(0).shape)  
print(x.unsqueeze(3).shape)   

torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 3, 1])


## Why you NEED this: neural networks expect a batch dimension. A single image of shape (3, 224, 224) must become (1, 3, 224, 224) — "a batch of 1 image" — before feeding it to a model. unsqueeze(0) adds that batch dimension

In [480]:
## permute() — reorder the dimensions
img = torch.rand(2, 3, 4)         # shape (2, 3, 4)
print(img.permute(2, 0, 1).shape) # torch.Size([4, 2, 3])

torch.Size([4, 2, 3])


## Why you NEED this — images!  Image libraries store images as (Height, Width, Channels) = HWC. But PyTorch wants (Channels, Height, Width) = CHW.

In [481]:
 #flatten() — collapse to 1D
# flatten - collapse to 1D
t = torch.rand(2, 3, 4)  # shape (2, 3, 4) = 24 numbers
print(t.flatten().shape)  # torch.Size([24]) - all in one line


torch.Size([24])


In [482]:
t

tensor([[[0.6304, 0.8881, 0.6839, 0.7368],
         [0.3881, 0.4794, 0.1581, 0.2317],
         [0.4470, 0.6137, 0.3944, 0.8261]],

        [[0.3653, 0.5637, 0.7196, 0.9115],
         [0.1713, 0.5104, 0.8606, 0.3289],
         [0.9269, 0.2478, 0.4558, 0.6005]]])

In [483]:
t.flatten(start_dim=1)   # keeps dim 0 (batch), flattens the rest
# shape (2, 3, 4) → (2, 12)   

tensor([[0.6304, 0.8881, 0.6839, 0.7368, 0.3881, 0.4794, 0.1581, 0.2317, 0.4470,
         0.6137, 0.3944, 0.8261],
        [0.3653, 0.5637, 0.7196, 0.9115, 0.1713, 0.5104, 0.8606, 0.3289, 0.9269,
         0.2478, 0.4558, 0.6005]])

## GPU Operations

In [484]:
#Move tensors and models to the GPU for fast computation.

In [485]:
# use GPU if available, else CPU
device = "cuda" if torch.cuda.is_available() else "cpu"

t = torch.rand(2, 3)
t = t.to(device)               # move tensor onto the GPU (or CPU)
print(t.device)               


cpu


## torch.from_numpy() — NumPy array → tensor

In [486]:
import numpy as np
arr = np.array([1, 2, 3])
t = torch.from_numpy(arr)    # now it's a tensor
print(t)                     
print(t.dtype)               

tensor([1, 2, 3])
torch.int64


In [487]:
a=torch.tensor([1,24,21])
print(a)
print(a.dtype)

tensor([ 1, 24, 21])
torch.int64


In [488]:
b=a.numpy()
print(b)
type(b)

[ 1 24 21]


numpy.ndarray

## Joining & Indexing


In [489]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

In [490]:
# Combine tensors into one
torch.stack([a, b])  # [[1,2],[3,4]] shape (2,2)

tensor([[1, 2],
        [3, 4]])

In [491]:
# cat - join along an EXISTING dimension (makes a longer tensor)
torch.cat([a, b])    # [1,2,3,4] (no new dimension)

tensor([1, 2, 3, 4])

In [492]:
# indexing & slicing (same syntax as NumPy/Python lists)
t = torch.tensor([[10,20,30],
                  [40,50,60]])
print(t[0])# first row -> [10,20,30]
print(t[0][1])       # row0, col1 -> 20
print(t[:, 0])       # all rows, col 0 -> [10,40]
print(t[1, :])       # row 1, all cols -> [40,50,60]
print(t[:, 1:3])     # all rows, cols 1-2 -> [[20,30],[50,60]]

tensor([10, 20, 30])
tensor(20)
tensor([10, 40])
tensor([40, 50, 60])
tensor([[20, 30],
        [50, 60]])
